### ISSUE TITLE
Use go modules instead of dep

### ISSUE THREAD

**Issue by itayd** [uber-common/cadence-samples#24]
Not sure if you have a policy around this, but moving to go modules is fairly simple, all that needs to be done is:

`$ go mod init github.com/uber-common/cadence-samples`

and remove the dep stage from the Makefile.

The motivation, at least for me is to avoid having to put stuff in a GOPATH.

btw, if this is ok with you, will be happy to do it.

**Comment by ernado** [comment]
Seems like it was resolved in #26 :)

**Comment by itayd** [comment]
Ha, same day.
