### ISSUE TITLE
During execution Expense example workflow timeout is 1 minute instead of 10 minutes

### ISSUE THREAD

**Issue by sandeepone** [uber-common/cadence-samples#30]
The timeout is suppose to be 10 minutes as per the options defined here:
https://github.com/uber-common/cadence-samples/blob/5dab89de4725538f0a106b85540d4346b04cc0e9/cmd/samples/expense/workflow.go#L40-L43

Instead it still 1 min and times out with WorkflowExecutionTimedOut : START_TO_CLOSE 
```
activityType.name : main.waitForDecisionActivity
taskList.name: expenseGroup
scheduleToCloseTimeout: 1m
scheduleToStartTimeout: 1m
startToCloseTimeout: 1m
heartbeatTimeout
```

**Comment by mfateev** [comment]
The timeout is the workflow timeout: https://github.com/uber-common/cadence-samples/blob/5dab89de4725538f0a106b85540d4346b04cc0e9/cmd/samples/expense/main.go#L28. 
So there is no bug. But I agree that having the activity timeout larger than the workflow timeout is senseless.

**Comment by sandeepone** [comment]
Thank you. I figured it out after checking the logs again.
